application:
  config:
    elasticsearchServiceName: aws-es-proxy-service
    feedbackServiceName: aws-es-proxy-service
    feedbackEndpoint: /prod-feedback/_doc
    analyticsSiteId: UA-152065860-4

ingress:
  enabled: true
  tlsEnabled: true
  hosts:
    - host: prisoner-content-hub-production.apps.live-1.cloud-platform.service.justice.gov.uk
    - host: cookhamwood.content-hub.prisoner.service.justice.gov.uk
      cert_secret: prisoner-content-hub-frontend-certificate
  path: /

