nameOverride: ""
fullnameOverride: ""

replicaCount: 1
maxReplicaCount: 3

tier: frontend

image:
  repository: mojdigitalstudio/prisoner-content-hub-frontend
  pullPolicy: IfNotPresent
  tag: latest

application:
  port: 3000
  liveness:
    endpoint: /games/smashout
    delaySeconds: 10
    timeoutSeconds: 5
  readiness:
    endpoint: /health
    delaySeconds: 10
    timeoutSeconds: 5
  config:
    appName: "HMP Berwyn"
    enableFeatureToggles: false
    enablePrisonSwitch: false
    mockAuth: false
    featureNewDesigns: false
    establishmentName: berwyn
    nprStream: /npr-stream
    analyticsEndpoint: https://www.google-analytics.com/collect
    useRelativeUrl: false
  contentConfigMap: prisoner-content-hub-drupal

imagePullSecrets: [] # Are we using ECR?

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

resources: {}

affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  tlsEnabled: false
  path: /
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
      SecRuleEngine On
