nameOverride: ""
fullnameOverride: ""

replicaCount: 3
maxReplicaCount: 6

tier: frontend

image:
  repository: quay.io/hmpps/prisoner-content-hub-frontend
  pullPolicy: IfNotPresent
  tag: latest

application:
  port: 3000
  liveness:
    endpoint: /health
    delaySeconds: 10
    timeoutSeconds: 5
  readiness:
    endpoint: /health/readiness
    delaySeconds: 10
    timeoutSeconds: 5
  contentConfigMapName: prisoner-content-hub-drupal
  nprConfigMapName: npr-live
  openSearchSecretName: pfs-opensearch-proxy-url

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  tlsEnabled: true
  path: /
  prefixes:
    - berwyn
    - cookhamwood
    - erlestoke
    - felthama
    - felthamb
    - garth
    - lindholme
    - newhall
    - ranby
    - stokeheath
    - styal
    - swaleside
    - themount
    - thestudio
    - wayland
    - werrington
    - wetherby
    - woodhill
  annotations:
    # nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    # nginx.ingress.kubernetes.io/modsecurity-snippet: |
    #   Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
    #   SecRuleEngine On
    nginx.ingress.kubernetes.io/server-snippet: |
       add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

