application:
  config:
    elasticsearchServiceName: aws-es-proxy-service
    feedbackServiceName: aws-es-proxy-service
    feedbackEndpoint: /prod-feedback/_doc
    enableFeatureToggles: true
    enablePrisonSwitch: true
    mockAuth: true
    analyticsSiteId: UA-152065860-4

ingress:
  enabled: false
  tlsEnabled: false
  hostName: pfs-hub.local
