nameOverride: ""
fullnameOverride: ""

replicaCount: 2
maxReplicaCount: 3

tier: frontend

image:
  repository: mojdigitalstudio/prisoner-content-hub-frontend
  pullPolicy: IfNotPresent
  tag: latest

application:
  port: 3000
  liveness:
    endpoint: /health
    delaySeconds: 10
    timeoutSeconds: 5
  readiness:
    endpoint: /health/readiness
    delaySeconds: 10
    timeoutSeconds: 5
  config:
    enablePersonalInformation: false
    establishmentName: berwyn
    analyticsEndpoint: https://www.google-analytics.com/collect
    elasticsearchIndexName: content_index
    enableRedisCache: false
  contentConfigMapName: prisoner-content-hub-drupal
  nprConfigMapName: npr-live
  dbSecretName: drupal-rds

prisonerAuthAD:
  callbackEndpoint: /auth/provider/callback

imagePullSecrets: [] # Are we using ECR?

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

resources: {}

affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  tlsEnabled: true
  path: /
  allowed:
    # Allow traffic coming from: Primary DP Egress, Secondary DP Egress, Studio (Sheffield), DSD VPN, Quantum (x3 ranges), Lucas Cairns (Home), ARK (x5 ranges), Prometheus (Azure), CP Live 1-3
    sheffieldoffice: "217.33.148.210/29"
    mojvpn: "81.134.202.29/32"
    health-kick: "35.177.252.195/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    blocka: "18.130.83.42/32"
    blockb: "52.56.168.163/32"
    blockc: "212.137.36.230/32"
    blockd: "62.25.109.197/32"
    blocke: "195.92.38.16/28"
    blockf: "188.210.212.86/32"
    blockg: "195.59.75.0/24"
    blockh: "194.33.192.0/25"
    blocki: "194.33.193.0/25"
    blockj: "194.33.196.0/25"
    blockk: "194.33.197.0/25"
    blockl: "51.143.132.235/32"
    blockm: "51.132.208.67/32"
    blockn: "51.132.208.80/32"
    blocko: "51.132.208.113/32"
    blockp: "51.132.208.122/32"
  annotations:
    # nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    # nginx.ingress.kubernetes.io/modsecurity-snippet: |
    #   Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
    #   SecRuleEngine On
    nginx.ingress.kubernetes.io/server-snippet: |
       add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

