application:
  config:
    elasticsearchServiceName: aws-es-proxy-service
    feedbackServiceName: aws-es-proxy-service
    feedbackEndpoint: /prod-feedback/_doc
    analyticsSiteId: UA-152065860-7
    mockAuthEnabled: false

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - pattern: "{{ .prison }}-prisoner-content-hub-staging.apps.live-1.cloud-platform.service.justice.gov.uk"
