image:
  pullPolicy: Always

application:
  config:
    elasticsearchServiceName: aws-es-proxy-service
    feedbackServiceName: aws-es-proxy-service
    feedbackEndpoint: /prod-feedback/_doc
    analyticsSiteId: UA-152065860-4

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - suffix: -prisoner-content-hub-development.apps.live-1.cloud-platform.service.justice.gov.uk
