application:
  config:
    elasticsearchServiceName: aws-es-proxy-service
    feedbackServiceName: aws-es-proxy-service
    feedbackEndpoint: /prod-feedback/_doc
    analyticsSiteId: UA-152065860-6
    mockAuthEnabled: false
    approvedVisitorsFeatureEnabled: false

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-frontend-prisoner-content-hub-production-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  # These are legacy, prison specific hostnames we want to deprecate
  hosts:
    - pattern: "{{ .prison }}.content-hub.prisoner.service.justice.gov.uk"
      cert_secret: prisoner-content-hub-frontend-certificate
    - pattern: "{{ .prison }}-prisoner-content-hub-production.apps.live.cloud-platform.service.justice.gov.uk"
  host:
      pattern: "content-hub.prisoner.service.justice.gov.uk"
      cert_secret: prisoner-content-hub-frontend-certificate
