nameOverride: ""
fullnameOverride: ""

replicaCount: 2
maxReplicaCount: 3

tier: frontend

image:
  repository: mojdigitalstudio/prisoner-content-hub-frontend
  pullPolicy: IfNotPresent
  tag: latest

application:
  port: 3000
  liveness:
    endpoint: /health/liveness
    delaySeconds: 10
    timeoutSeconds: 5
  readiness:
    endpoint: /health/readiness
    delaySeconds: 10
    timeoutSeconds: 5
  config:
    appName: "HMP Berwyn"
    enableFeatureToggles: false
    enablePrisonSwitch: false
    mockAuth: false
    enablePersonalInformation: false
    establishmentName: berwyn
    analyticsEndpoint: https://www.google-analytics.com/collect
    useRelativeUrlForMedia: false
    elasticsearchIndexName: content_index
    enableRedisCache: false
  contentConfigMapName: prisoner-content-hub-drupal
  nprConfigMapName: npr-live
  dbSecretName: drupal-rds

imagePullSecrets: [] # Are we using ECR?

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

resources: {}

affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  tlsEnabled: true
  path: /
  annotations:
    # nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    # nginx.ingress.kubernetes.io/modsecurity-snippet: |
    #   Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
    #   SecRuleEngine On
    # Allow traffic coming from: Primary DP Egress, Secondary DP Egress, Studio (Sheffield), DSD VPN, Quantum (x3 ranges), Lucas Cairns (Home), ARK (x5 ranges), Prometheus (Azure)
    nginx.ingress.kubernetes.io/whitelist-source-range: 18.130.83.42/32,52.56.168.163/32,217.33.148.210/29,81.134.202.29/32,212.137.36.230/32,62.25.109.197/32,195.92.38.16/28,188.210.212.86/32,195.59.75.0/24,194.33.192.0/25,194.33.193.0/25,194.33.196.0/25,194.33.197.0/25,51.143.132.235/32
    nginx.ingress.kubernetes.io/server-snippet: |
       add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

