image:
  pullPolicy: Always

application:
  config:
    feedbackEndpoint: /prod-feedback/_doc
    analyticsSiteId: G-0RBPFCWD3X
    googleTagManagerSiteId: GTM-M62TTBK
    mockAuthEnabled: true

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-frontend-prisoner-content-hub-development-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  # These are legacy, prison specific hostnames we want to deprecate
  hosts:
    - pattern: "{{ .prison }}-prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk"
  host:
      pattern: "prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: hmpps-launchpad-nonprod
