application:
  config:
    feedbackEndpoint: /prod-feedback/_doc
    analyticsSiteId: G-FVRKLRH5PJ
    googleTagManagerSiteId: GTM-M62TTBK
    mockAuthEnabled: false

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-frontend-prisoner-content-hub-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts:
    - pattern: "{{ .prison }}-prisoner-content-hub-staging.apps.live.cloud-platform.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: hmpps-launchpad-nonprod
