image:
  pullPolicy: Always

application:
  config:
    elasticsearchServiceName: aws-es-proxy-service
    feedbackServiceName: aws-es-proxy-service
    feedbackEndpoint: /prod-feedback/_doc
    enableFeatureToggles: true
    analyticsSiteId: UA-152065860-4
    enablePersonalInformation: true
    azureAdFailedAuthUrl: /content/6291

ingress:
  annotations:
    kubernetes.io/ingress.class: prisoner-content-hub-development
  hosts:
    - suffix: -prisoner-content-hub-development.apps.live-1.cloud-platform.service.justice.gov.uk
