nameOverride: ""
fullnameOverride: ""

replicaCount: 1
maxReplicaCount: 3

image:
  repository: mojdigitalstudio/digital-hub-node
  pullPolicy: IfNotPresent
  tag: latest

application:
  port: 80
  liveness:
    endpoint: /api/health
    delaySeconds: 10
    timeoutSeconds: 5
  readiness:
    endpoint: /
    delaySeconds: 10
    timeoutSeconds: 5
  config:
    hubApiEndpoint: https://content.pfs-digital-hub-stage.hmpps.dsd.io/
    backEndUrl: http://some.domain
    nomisApiEndpoint: https://gateway.t3.nomis-api.hmpps.dsd.io
    appName: HMP Local
    enableFeatureToggles: true
    enablePrisonSwitch: true
    mockAuth: true
    elasticSearchEndpoint: http://localhost:9200
    featureNewDesigns: false
    establishmentName: berwyn
  nomisApiToken: drupal-rds

imagePullSecrets: [] # Are we using ECR?

podSecurityContext: {}

securityContext: {}

resources: {}

affinity: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  tlsEnabled: false
  hostName: content.pfs-hub.local
  path: /
  cert_secret: cert-secret
