version: "3.5"
services:
  frontend:
    image: quay.io/hmpps/prisoner-content-hub-frontend
    build:
      context: .
    env_file:
      - prisoner-content-hub-frontend.env
    ports:
      - 3000:3000
    networks:
      - prisoner_content_hub
  frontend-redis:
    image: 'bitnami/redis:5.0'
    networks:
      - prisoner_content_hub
    container_name: hub-frontend-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6378:6378'

networks:
  prisoner_content_hub:
    name: prisoner_content_hub
