defaults: &defaults
  working_directory: ~/prisoner-content-hub-frontend
  docker:
    - image: mojdigitalstudio/circleci-build-container
default_machine: &default_machine
  machine:
    enabled: true
  working_directory: ~/prisoner-content-hub-frontend
master_branch: &master_branch
  filters:
    branches:
      only: master
feature_branch: &feature_branch
  filters:
    branches:
      ignore: master

version: 2.1
commands:
  deploy_to_environment:
    description: "Deploy build to environment"
    parameters:
      to:
        type: string
        default: latest
    steps:
      - attach_workspace: &attach_workspace
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "36:39:b2:8b:1a:6e:03:37:69:91:58:c4:fe:81:fe:d9"
      - run:
          name: Deploy to Development
          command: |
            export VERSION_TO_DEPLOY="$(cat /tmp/workspace/docker-build/version-to-deploy.txt)" && \
            ssh -t ciuser@pfs-management-bastion-1.uksouth.cloudapp.azure.com ssh -t ciuser@<< parameters.to >>.pfs-management.com "sudo /etc/docker-decomposed-secrets.sh -v ${VERSION_TO_DEPLOY}"

jobs:
  test_branch:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/prisoner-content-hub-frontend
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Unit and Integration tests
          command: npm run lint && npm run test
  preview_build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build frontend Docker image
          command: |
            BUILD_NUMBER="$CIRCLE_BUILD_NUM" \
            GIT_REF="$CIRCLE_SHA1" \
            GIT_DATE="$(git log --format=%cd -n1 --date=iso $CIRCLE_SHA1)" \
            make build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Push frontend Docker image
          command: make push-preview
      - add_ssh_keys:
          fingerprints:
            - "0a:04:a1:27:17:3e:3d:8a:20:91:79:a1:9e:af:85:6c"
      - run:
          name: Save build number (for deployment)
          command: |
            mkdir -p /tmp/workspace/docker-build
            cd /tmp/workspace/docker-build
            echo preview > version-to-deploy.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-build
  preview_build_deploy_dev:
    <<: *default_machine
    steps:
      - deploy_to_environment:
          to: hub-dev
  preview_build_deploy_stage:
    <<: *default_machine
    steps:
      - deploy_to_environment:
          to: hub-stage
  build_frontend:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build frontend Docker image
          command: |
            BUILD_NUMBER="$CIRCLE_BUILD_NUM" \
            GIT_REF="$CIRCLE_SHA1" \
            GIT_DATE="$(git log --format=%cd -n1 --date=iso $CIRCLE_SHA1)" \
            make build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Push frontend Docker image
          command: make push
      - add_ssh_keys:
          fingerprints:
            - "0a:04:a1:27:17:3e:3d:8a:20:91:79:a1:9e:af:85:6c"
      - run:
          name: Create Git Tag
          command: |
            git config user.name "Circle CI"
            git config user.email "circle@circleci.com"
            git tag -a "$(date '+%d-%m-%Y')-$CIRCLE_BUILD_NUM" $CIRCLE_SHA1 -m "$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=%B)"
            git push origin "$(date '+%d-%m-%Y')-$CIRCLE_BUILD_NUM"
      - run:
          name: Save build number (for deployment)
          command: |
            mkdir -p /tmp/workspace/docker-build
            cd /tmp/workspace/docker-build
            echo build-${CIRCLE_BUILD_NUM} > version-to-deploy.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-build
  # run_e2e_test:
  #   docker:
  #     - image: circleci/node:12-browsers
  #   working_directory: /home/circleci/app
  #   steps:
  #     - checkout
  #     - run:
  #         name: Update NPM
  #         command: "sudo npm install -g npm@latest"
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #     - run:
  #         name: Install dependencies
  #         command: npm ci
  #     - save_cache:
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #         paths:
  #           - ./node_modules
  #     - run:
  #         name: Run E2E tests against Staging
  #         command: |
  #           npm run build && \
  #           BUILD_NUMBER="$CIRCLE_BUILD_NUM" \
  #           GIT_REF="$CIRCLE_SHA1" \
  #           GIT_DATE="$(git log --format=%cd -n1 --date=iso $CIRCLE_SHA1)" \
  #           npm run record-build-info && \
  #           APP_NAME="HMP Local" \
  #           NODE_ENV=production \
  #           MATOMO_URL="foo.bar" \
  #           MATOMO_TOKEN="foobar" \
  #           MATOMO_API_URI="http://hub-matomo" \
  #           ENABLE_PRISON_SWITCH="true" \
  #           HUB_API_ENDPOINT="http://pfs-stage-hub-1.uksouth.cloudapp.azure.com:11001" \
  #           ELASTICSEARCH_ENDPOINT="UNSET" \
  #           ESTABLISHMENT_NAME="berwyn" \
  #           NOMIS_API_ENDPOINT="https://foo.bar" \
  #           FEEDBACK_URL="http://foo.bar" \
  #           npm run test:e2e:run
  #     - store_artifacts:
  #         path: ./cypress/videos
  #     - store_artifacts:
  #         path: ./cypress/screenshots
  deploy_dev:
    <<: *default_machine
    steps:
      - deploy_to_environment:
          to: hub-dev
  deploy_stage:
    <<: *default_machine
    steps:
      - deploy_to_environment:
          to: hub-stage
  deploy_prod:
    <<: *default_machine
    steps:
      - attach_workspace: &attach_workspace
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "36:39:b2:8b:1a:6e:03:37:69:91:58:c4:fe:81:fe:d9"
      - run:
          name: Deploy to Production
          command: |
            export VERSION_TO_DEPLOY="$(cat /tmp/workspace/docker-build/version-to-deploy.txt)" && \
            ssh -t ciuser@pfs-management-bastion-1.uksouth.cloudapp.azure.com ssh -t ciuser@hub-wayland-prod.pfs-management.com "sudo /etc/docker-decomposed-secrets.sh -v ${VERSION_TO_DEPLOY}" && \
            ssh -t ciuser@pfs-management-bastion-1.uksouth.cloudapp.azure.com ssh -t ciuser@hub-berwyn-prod.pfs-management.com "sudo /etc/docker-decomposed-secrets.sh -v ${VERSION_TO_DEPLOY}"
            # ssh -t ciuser@pfs-management-bastion-1.uksouth.cloudapp.azure.com ssh -t ciuser@hub-cookhamwood-prod.pfs-management.com "sudo /etc/docker-decomposed-secrets.sh -v ${VERSION_TO_DEPLOY}"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test_branch:
          <<: *feature_branch
      - approve_preview_build:
          <<: *feature_branch
          type: approval
      - preview_build:
          <<: *feature_branch
          requires:
            - test_branch
            - approve_preview_build
      - preview_build_deploy_dev:
          <<: *feature_branch
          requires:
            - preview_build
      - approve_preview_build_deploy_stage:
          <<: *feature_branch
          type: approval
          requires:
            - preview_build_deploy_dev
      - preview_build_deploy_stage:
          <<: *feature_branch
          requires:
            - approve_preview_build_deploy_stage
      - build_frontend:
          <<: *master_branch
      # - run_e2e_test:
      #     <<: *master_branch
      #     requires:
      #       - build_frontend
      - deploy_dev:
          <<: *master_branch
          requires:
            - build_frontend
      - approve_deploy_stage:
          <<: *master_branch
          type: approval
          requires:
            - deploy_dev
      - deploy_stage:
          <<: *master_branch
          requires:
            - approve_deploy_stage
      - approve_deploy_prod:
          <<: *master_branch
          type: approval
          requires:
            - deploy_stage
      - deploy_prod:
          <<: *master_branch
          requires:
            - approve_deploy_prod
