main_branch: &main_branch
  filters:
    branches:
      only: main
feature_branch: &feature_branch
  filters:
    branches:
      ignore: main

version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.2
  helm: circleci/helm@1.2.0
  hmpps: ministryofjustice/hmpps@3.2
  slack: circleci/slack@4.4.2

executors:
  build_executor:
    docker:
    - image: mojdigitalstudio/circleci-build-container
    working_directory: ~/workspace
  test_executor:
    docker:
      - image: circleci/node:14-buster-browsers
    working_directory: ~/workspace

commands:
  release_to_namespace:
    description: "Release with Helm"
    parameters:
      environment:
        type: string
      releaseName:
        type: string
      qualifier:
        type: string  
    steps:
      - attach_workspace:
          at: /tmp/build-info
      - run:
          name: Release to << parameters.environment >>
          command: |
            VERSION_TO_DEPLOY=$(cat /tmp/build-info/version-to-deploy.txt)
            sed -i "s/appVersion:.*/appVersion: \"${VERSION_TO_DEPLOY}\"/g" "./helm_deploy/prisoner-content-hub-frontend/Chart.yaml"
            QUALIFIER=<< parameters.qualifier >>
            RELEASE_NAME=<< parameters.releaseName >>${QUALIFIER:+-$QUALIFIER}
            helm upgrade $RELEASE_NAME ./helm_deploy/prisoner-content-hub-frontend \
              --install --wait --force --reset-values --timeout 360s \
              --namespace=${KUBE_NAMESPACE} \
              --values ./helm_deploy/prisoner-content-hub-frontend/values-<< parameters.environment >>.yaml \
              --set application.contentConfigMapName="${HELM_BACKEND_RELEASE_NAME}" \
              --set application.nprConfigMapName="${HELM_NPR_CONFIG_MAP_NAME}" \
              --set application.sentry_dsn="${FRONTEND_SENTRY_DSN}" \
              --set application.sentry_environment="<< parameters.environment >>" \
              --set application.sentry_release="${VERSION_TO_DEPLOY}" \
              --set hmppsAuthClientId="${HMPPS_AUTH_CLIENT_ID}" \
              --set hmppsAuthClientSecret="${HMPPS_AUTH_CLIENT_SECRET}" \
              --set hmppsAuthBaseUrl="${HMPPS_AUTH_BASE_URL}" \
              --set prisonApiBaseUrl="${PRISON_API_BASE_URL}" \
              --set cacheSecret="${CACHE_SECRET}" \
              --set prisonerAuthAD.clientId=${AZURE_AD_CLIENT_ID} \
              --set prisonerAuthAD.clientSecret=${AZURE_AD_CLIENT_SECRET} \
              --set hotJarId=${HOTJAR_ID} \
              --set image.tag=${VERSION_TO_DEPLOY} \
              --set ingress.qualifier="<< parameters.qualifier >>"

jobs:
  build:
    executor:
      name: hmpps/node
      tag: 14.15-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.cache
      - run:
          command:
            npm run build
      - run:
          name: Linter check
          command: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - assets/stylesheets
            - .cache/Cypress

  run_unit_tests:
    executor: test_executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run Unit and Integration tests
          command: npm run test
      - run:
          name: Lint code
          command: npm run lint

  run_e2e_tests:
    executor: test_executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run the node app.
          command: npm run start:e2e
          background: true
      - run:
          name: Get wiremock
          command: curl -o wiremock.jar https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.27.2/wiremock-standalone-2.27.2.jar
      - run:
          name: Run wiremock
          command: java -jar wiremock.jar --port 9091
          background: true
      - run:
          name: Wait for node app to start
          command: sleep 5
      - run:
          name: e2e tests
          command: npm run test:e2e:ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/artifacts/videos
      - store_artifacts:
          path: cypress/artifacts/screenshots

  build_preview:
    executor: build_executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - hmpps/create_app_version
      - run:
          name: Build frontend Docker image
          command: |
            GIT_REF="$CIRCLE_SHA1" \
            GIT_DATE="$(git log --format=%cd -n1 --date=iso $CIRCLE_SHA1)" \
            make build
      - run:
          name: Push frontend Docker image
          command: make push-preview
      - add_ssh_keys:
          fingerprints:
            - "0a:04:a1:27:17:3e:3d:8a:20:91:79:a1:9e:af:85:6c"
      - run:
          name: Save build number (for deployment)
          command: |
            mkdir -p /tmp/build-info
            echo $APP_VERSION > /tmp/build-info/version-to-deploy.txt
      - persist_to_workspace:
          root: /tmp/build-info
          paths:
            - version-to-deploy.txt

  build_production:
    executor: build_executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - hmpps/create_app_version
      - run:
          name: Build frontend Docker image
          command: |
            BUILD_NUMBER="$APP_VERSION" \
            GIT_REF="$CIRCLE_SHA1" \
            GIT_DATE="$(git log --format=%cd -n1 --date=iso $CIRCLE_SHA1)" \
            make build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Push frontend Docker image
          command: make push
      - add_ssh_keys:
          fingerprints:
            - "0a:04:a1:27:17:3e:3d:8a:20:91:79:a1:9e:af:85:6c"
      - run:
          name: Create Git Tag
          command: |
            git config user.name "Circle CI"
            git config user.email "circle@circleci.com"
            git tag -a "$APP_VERSION" $CIRCLE_SHA1 -m "$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=%B)"
            git push origin "$APP_VERSION"
      - run:
          name: Save build number (for deployment)
          command: |
            mkdir -p /tmp/build-info
            echo ${APP_VERSION} > /tmp/build-info/version-to-deploy.txt
      - persist_to_workspace:
          root: /tmp/build-info
          paths:
            - version-to-deploy.txt

  deploy_cloud_platform:
    executor: build_executor
    parameters:
      environment:
        type: string
      qualifier:
        type: string
        default: ""    
    steps:
      - checkout
      - hmpps/k8s_setup:
          ca-cert: KUBE_CLUSTER_CERT
          cluster-name: KUBE_CLUSTER_NAME
          kube-namespace: KUBE_NAMESPACE
          kube-token: KUBE_TOKEN
      - hmpps/install_helm
      - release_to_namespace:
          environment: "<< parameters.environment >>"
          releaseName: "prisoner-content-hub-frontend"
          qualifier: "<< parameters.qualifier >>"
      - slack/notify:
          channel: hub-test-releases
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${CIRCLE_PROJECT_REPONAME}* version `${APP_VERSION}` deploy to *<< parameters.environment >>*"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View job"
                    },
                    "url": "${CIRCLE_BUILD_URL}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": ":circleci-${CCI_STATUS}: Deploy ${CCI_STATUS}"
                    },
                    {
                      "type": "plain_text",
                      "text": "\n${DEPLOYMENT_CHANGELOG_JSON}"
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - run_unit_tests:
          requires:
            - build
      - run_e2e_tests:
          requires:
            - build
      - build_preview:
          <<: *feature_branch

      - deploy_cloud_platform:
          <<: *feature_branch
          context:
            - hmpps-common-vars
            - prisoner-content-hub-development
          environment: "development"
          qualifier: "${CIRCLE_PULL_REQUEST##*/}"
          requires:
            - build_preview

      - build_production:
          <<: *main_branch
          requires:
            - run_unit_tests
            - run_e2e_tests

      - deploy_cloud_platform:
          <<: *main_branch
          context: 
            - hmpps-common-vars
            - prisoner-content-hub-staging
          name: deploy_to_staging
          environment: "staging"
          requires:
            - build_production

      - approve_deploy_production:
          <<: *main_branch
          type: approval
          requires:
            - deploy_to_staging

      - deploy_cloud_platform:
          <<: *main_branch
          context: 
            - hmpps-common-vars
            - prisoner-content-hub-prod
          environment: "production"
          requires:
            - approve_deploy_production

  security:
    triggers:
      - schedule:
          cron: "0 6 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/npm_security_audit:
          slack_channel: hub_frontend
          context:
            - hmpps-common-vars
      - hmpps/veracode_policy_scan:
          slack_channel: hub_frontend
          context:
            - hmpps-common-vars
            - veracode-credentials
