module.exports = {
  activity: (date, startTime, endTime, description, location) => ({
    bookingId: 6699,
    eventClass: 'INT_MOV',
    eventId: 438561726,
    eventStatus: 'SCH',
    eventType: 'PRISON_ACT',
    eventTypeDesc: 'Prison Activities',
    eventSubType: 'PA',
    eventSubTypeDesc: 'Prison Activities',
    eventDate: date,
    startTime: `${date}T${startTime}`,
    endTime: `${date}T${endTime}`,
    eventLocation: location,
    eventLocationId: 124814,
    eventSource: 'PA',
    eventSourceCode: 'TV PROD',
    eventSourceDesc: description,
    paid: false,
    payRate: 1.21,
    locationCode: 'NEDUC',
  }),

  appointment: (date, startTime, endTime, description, location) => ({
    bookingId: 6699,
    eventClass: 'INT_MOV',
    eventStatus: 'SCH',
    eventType: 'APP',
    eventTypeDesc: 'Appointment',
    eventSubType: 'GYMF',
    eventSubTypeDesc: description,
    eventDate: date,
    startTime: `${date}T${startTime}`,
    endTime: `${date}T${endTime}`,
    eventLocation: location,
    eventSource: 'APP',
    eventSourceCode: 'APP',
    eventSourceDesc: 'dadsdas',
  }),
};
