apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
  labels:
    {{- include "prisoner-content-hub-frontend.labels" . | nindent 4 }}
data:
  internalUrl: {{ include "prisoner-content-hub-frontend.internalHost" . }}
  externalUrl: {{ include "prisoner-content-hub-frontend.externalHost" . }}
