apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
  labels:
    {{- include "prisoner-content-hub-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  selector:
    matchLabels:
      {{- include "prisoner-content-hub-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prisoner-content-hub-frontend.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.application.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.application.liveness.endpoint }}
              port: http
            initialDelaySeconds: {{ .Values.application.liveness.delaySeconds }}
            timeoutSeconds: {{ .Values.application.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.application.readiness.endpoint }}
              port: http
            initialDelaySeconds: {{ .Values.application.readiness.delaySeconds }}
            timeoutSeconds: {{ .Values.application.readiness.timeoutSeconds }}
{{ include "deployment.envs" . | nindent 10 }}