apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
  labels:
    {{- include "prisoner-content-hub-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prisoner-content-hub-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prisoner-content-hub-frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HMPPS_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
                  key: hmppsAuthClientId
            - name: HMPPS_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
                  key: hmppsAuthClientSecret
            - name: HMPPS_AUTH_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
                  key: hmppsAuthBaseUrl
            - name: PRISON_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
                  key: prisonApiBaseUrl
            - name: HUB_API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.application.contentConfigMapName }}
                  key: internalUrl
            - name: ELASTICSEARCH_ENDPOINT
              value: {{ include "prisoner-content-hub-frontend.elasticsearchServiceHost" . }}
            - name: ELASTICSEARCH_INDEX_NAME
              value: {{ .Values.application.config.elasticsearchIndexName }}
            - name: DRUPAL_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.application.dbSecretName }}
                  key: database_name
            - name: ENABLE_PERSONAL_INFORMATION
              value: {{ .Values.application.config.enablePersonalInformation | quote }}
            - name: FEEDBACK_URL
              value: {{ include "prisoner-content-hub-frontend.feedbackUrl" . }}
            - name: NPR_STREAM
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.application.nprConfigMapName }}
                  key: externalUrl
            - name: ANALYTICS_ENDPOINT
              value: {{ .Values.application.config.analyticsEndpoint }}
            - name: ANALYTICS_ENDPOINT
              value: {{ .Values.application.config.analyticsEndpoint }}
            - name: ANALYTICS_SITE_ID
              value: {{ .Values.application.config.analyticsSiteId }}
            - name: SENTRY_DSN
              value: {{ .Values.application.sentry_dsn }}
            - name: ENABLE_REDIS_CACHE
              value: {{ .Values.application.config.enableRedisCache | quote }}
            - name: CACHE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
                  key: cacheSecret
            - name: AZURE_AD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
                  key: azureAdClientId
            - name: AZURE_AD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
                  key: azureAdClientSecret
            - name: AZURE_AD_CALLBACK_PATH
              value: {{ .Values.prisonerAuthAD.callbackEndpoint }}
          ports:
            - name: http
              containerPort: {{ .Values.application.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.application.liveness.endpoint }}
              port: http
            initialDelaySeconds: {{ .Values.application.liveness.delaySeconds }}
            timeoutSeconds: {{ .Values.application.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.application.readiness.endpoint }}
              port: http
            initialDelaySeconds: {{ .Values.application.readiness.delaySeconds }}
            timeoutSeconds: {{ .Values.application.readiness.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
