{{- if .Values.ingress.enabled -}}
{{- $fullName := include "prisoner-content-hub-frontend.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "prisoner-content-hub-frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tlsEnabled }}
  tls:
    - hosts:
        - {{ include "prisoner-content-hub-frontend.hostName" . }}
  {{- end }}
  rules:
    - host: {{ include "prisoner-content-hub-frontend.hostName" . }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
