{{- if .Values.ingress.enabled -}}
{{- $fullName := include "prisoner-content-hub-frontend.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "prisoner-content-hub-frontend.labels" . | nindent 4 }}
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ tpl $v (dict "Template" $.Template) | quote }}
    {{- end}}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ include "app.joinListWithComma" .Values.ingress.allowed | quote }}
spec:
  ingressClassName: default
  tls:
  - hosts:
  {{- range .Values.ingress.hosts }}
  {{- $certSecret := .cert_secret -}}
  {{- $domainPattern := .pattern }}
    {{- range $.Values.ingress.prefixes }}
      - {{ tpl $domainPattern (dict "prison" . "Template" $.Template) }}
    {{- end }}
      {{ if .cert_secret }}secretName: {{ .cert_secret }}{{ end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    {{- $domainPattern := .pattern -}}
    {{- range $.Values.ingress.prefixes }}
    - host: {{ tpl $domainPattern (dict "prison" . "Template" $.Template) }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
    {{- end }}
  {{- end }}
{{- end }}
