{{- if .Values.ingress.enabled -}}
{{- $fullName := include "prisoner-content-hub-frontend.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "prisoner-content-hub-frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  {{- $domainPrefix := .Values.ingress.domainPrefix -}}
  {{- range .Values.ingress.hosts }}
  - hosts:
    - {{ $domainPrefix }}{{ .suffix }}
    {{ if .cert_secret }}secretName: {{ .cert_secret }}{{ end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ $domainPrefix }}{{ .suffix }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
