{{- if .Values.ingress.enabled -}}
{{- $fullName := include "prisoner-content-hub-frontend.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "prisoner-content-hub-frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ include "app.joinListWithComma" .Values.ingress.allowed | quote }}
spec:
  tls:
  {{- $domainPrefix := .Values.ingress.domainPrefix -}}
  {{- range .Values.ingress.hosts }}
    {{- $domainSuffix := .suffix -}}
  - hosts:
    {{- range $.Values.ingress.prefix }}
    - {{ .siteName }}{{ $domainSuffix }}
    {{ if .cert_secret }}secretName: {{ .cert_secret }}{{ end }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    {{- $domainSuffix := .suffix -}}
    {{- range $.Values.ingress.prefix }}
    - host: {{ .siteName }}{{ $domainSuffix }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{- end }}
  {{- end }}
{{- end }}
