apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
  labels:
    {{- include "prisoner-content-hub-frontend.labels" . | nindent 4 }}
data:
  hmppsAuthClientId: {{ .Values.hmppsAuthClientId | b64enc }}
  hmppsAuthClientSecret: {{ .Values.hmppsAuthClientSecret | b64enc }}
  hmppsAuthBaseUrl: {{ .Values.hmppsAuthBaseUrl | b64enc }}
  prisonApiBaseUrl: {{ .Values.prisonApiBaseUrl | b64enc }}
  prisonerContactRegistryApiBaseUrl: {{ .Values.prisonerContactRegistryApiBaseUrl | b64enc }}
  incentivesApiBaseUrl: {{ .Values.incentivesApiBaseUrl | b64enc }}
  adjudicationsApiBaseUrl: {{ .Values.adjudicationsApiBaseUrl | b64enc }}
  cacheSecret: {{ .Values.cacheSecret | b64enc }}
  azureAdClientId: {{ .Values.prisonerAuthAD.clientId | b64enc }}
  azureAdClientSecret: {{ .Values.prisonerAuthAD.clientSecret | b64enc }}
  appInsightsSecret: {{ .Values.appInsightsSecret | b64enc }}
