apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
  labels:
    {{- include "prisoner-content-hub-frontend.labels" . | nindent 4 }}
data:
  cacheSecret: {{ .Values.cacheSecret | b64enc }}
  appInsightsSecret: {{ .Values.appInsightsSecret | b64enc }}
  feedbackDatabaseName: {{ .Values.feedbackDatabaseName | b64enc }}
  feedbackDatabaseUrl: {{ .Values.feedbackDatabaseUrl | b64enc }}
  feedbackDatabaseUserName: {{ .Values.feedbackDatabaseUserName | b64enc }}
  feedbackDatabasePassword: {{ .Values.feedbackDatabasePassword | b64enc }}
