apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
  labels:
    {{- include "prisoner-content-hub-frontend.labels" . | nindent 4 }}
data:
  hmppsAuthClientId: {{ .Values.hmppsAuthClientId | b64enc }}
  hmppsAuthClientSecret: {{ .Values.hmppsAuthClientSecret | b64enc }}
  hmppsAuthBaseUrl: {{ .Values.hmppsAuthBaseUrl | b64enc }}
  prisonApiBaseUrl: {{ .Values.prisonApiBaseUrl | b64enc }}
