apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "prisoner-content-hub-frontend.fullname" . }}
  labels:
    {{- include "prisoner-content-hub-frontend.labels" . | nindent 4 }}
data:
  nomisApiToken: {{ .Values.nomisApiToken | quote | b64enc }}
  nomisApiEndpoint: {{ .Values.nomisApiEndpoint | quote | b64enc }}
